// Author: Yash Deshpande
// Date  : 17-07-2026

/*
DISCLAIMER: The explanation below was generated by an LLM.
Model : Claude Opus 4.8 (Claude Code)
Date  : 17-07-2026
*/

/*
================================================================================
WHAT IS ELF ?
================================================================================
ELF stands for Executable and Linkable Format. It is the standard file format
for programs on Linux (and most Unix-like systems).

Think of it as the "container format" for compiled code -- just like .mp4 is a
container for video, ELF is the container for machine code.

--------------------------------------------------------------------------------
THE SIMPLEST ANALOGY
--------------------------------------------------------------------------------
When you compile your C++ file:

    hello.cpp  -->  (compiler)  -->  hello     <-- this is an ELF file

That 'hello' binary isn't just raw CPU instructions dumped in a file. It is
organized into labeled sections so the operating system knows exactly how to
load and run it.

--------------------------------------------------------------------------------
WHAT'S INSIDE AN ELF FILE
--------------------------------------------------------------------------------
    Header        --> "I am an ELF file, I'm 64-bit, here's where to start"
    .text         --> Your actual code (machine instructions)
    .data         --> Initialized global variables      (e.g. int x = 5;)
    .bss          --> Uninitialized globals             (e.g. int y;)
    .rodata       --> Read-only constants               (e.g. "hello")
    Symbol table  --> Names of functions/variables (for linking & debugging)

--------------------------------------------------------------------------------
WHICH FILES ARE ELF ?
--------------------------------------------------------------------------------
Not just executables. ELF covers several types:
    Executables       --> your final ./a.out program
    Object files (.o) --> output of compiling one .cpp, before linking
    Shared libs (.so) --> like .dll on Windows

--------------------------------------------------------------------------------
THE "LINKABLE" PART
--------------------------------------------------------------------------------
The name has two halves:
    Executable  --> the OS can RUN it.
    Linkable    --> the linker can COMBINE it with other pieces.

This is why you can compile files separately and link them together:

    a.cpp --> a.o  --+
                     +--> (linker) --> program     (all ELF files)
    b.cpp --> b.o  --+

--------------------------------------------------------------------------------
TRY IT YOURSELF
--------------------------------------------------------------------------------
    ROOT=$(git rev-parse --show-toplevel)     // repo root, works from anywhere inside the repo
    g++ "$ROOT/hello_world.cpp" -o "$ROOT/hello_world"
    file "$ROOT/hello_world"          // -> "ELF 64-bit LSB executable..."
    readelf -h "$ROOT/hello_world"    // shows the ELF header
    readelf -S "$ROOT/hello_world"    // lists all the sections (linker's view)
    readelf -l "$ROOT/hello_world"    // lists program headers / LOAD segments (loader's view)

--------------------------------------------------------------------------------
IN ONE LINE
--------------------------------------------------------------------------------
ELF is the structured file format Linux uses to store compiled programs,
organized into labeled sections so the OS and linker know how to load, link,
and run your code.

NOTE: readelf (see 2_tool_gnu_binutils.c) is literally the tool for READing
ELF files.
================================================================================
*/

/*
================================================================================
EXTRA NOTES : SAMPLE OUTPUT
================================================================================
Below is the actual output captured by running the two commands above on the
compiled ./hello_world binary (x86-64 Linux / WSL2).

--------------------------------------------------------------------------------
$ readelf -h ./hello_world          (the ELF Header)
--------------------------------------------------------------------------------
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Position-Independent Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x1080
  Start of program headers:          64 (bytes into file)
  Start of section headers:          14520 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         13
  Size of section headers:           64 (bytes)
  Number of section headers:         31
  Section header string table index: 30

  Notes:
    - Magic starts with 7f 45 4c 46  ==  0x7F 'E' 'L' 'F'  (the ELF signature).
    - Type DYN / PIE  ==  Position-Independent Executable (modern default; the
      OS can load it at a randomized base address for security/ASLR).

--------------------------------------------------------------------------------
$ readelf -S ./hello_world          (the Section Headers)
--------------------------------------------------------------------------------
There are 31 section headers, starting at offset 0x38b8:

  [Nr] Name              Type             Address           Offset
  [ 0]                   NULL             0000000000000000  00000000
  [ 1] .interp           PROGBITS         0000000000000318  00000318
  [ 2] .note.gnu.pr[...] NOTE             0000000000000338  00000338
  [ 3] .note.gnu.bu[...] NOTE             0000000000000368  00000368
  [ 4] .note.ABI-tag     NOTE             000000000000038c  0000038c
  [ 5] .gnu.hash         GNU_HASH         00000000000003b0  000003b0
  [ 6] .dynsym           DYNSYM           00000000000003d8  000003d8
  [ 7] .dynstr           STRTAB           00000000000004e0  000004e0
  [ 8] .gnu.version      VERSYM           000000000000063e  0000063e
  [ 9] .gnu.version_r    VERNEED          0000000000000658  00000658
  [10] .rela.dyn         RELA             00000000000006b8  000006b8
  [11] .rela.plt         RELA             00000000000007a8  000007a8
  [12] .init             PROGBITS         0000000000001000  00001000
  [13] .plt              PROGBITS         0000000000001020  00001020
  [14] .plt.got          PROGBITS         0000000000001050  00001050
  [15] .plt.sec          PROGBITS         0000000000001060  00001060
  [16] .text             PROGBITS         0000000000001080  00001080  <-- code
  [17] .fini             PROGBITS         00000000000011a4  000011a4
  [18] .rodata           PROGBITS         0000000000002000  00002000  <-- constants
  [19] .eh_frame_hdr     PROGBITS         0000000000002018  00002018
  [20] .eh_frame         PROGBITS         0000000000002050  00002050
  [21] .init_array       INIT_ARRAY       0000000000003d98  00002d98
  [22] .fini_array       FINI_ARRAY       0000000000003da0  00002da0
  [23] .dynamic          DYNAMIC          0000000000003da8  00002da8
  [24] .got              PROGBITS         0000000000003fa8  00002fa8
  [25] .data             PROGBITS         0000000000004000  00003000  <-- init globals
  [26] .bss              NOBITS           0000000000004040  00003010  <-- uninit globals
  [27] .comment          PROGBITS         0000000000000000  00003010
  [28] .symtab           SYMTAB           0000000000000000  00003040  <-- symbol table
  [29] .strtab           STRTAB           0000000000000000  00003448
  [30] .shstrtab         STRTAB           0000000000000000  0000379d

Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  D (mbind), l (large), p (processor specific)

  Notes:
    - You can spot the theory sections from above living in the real binary:
      .text (code), .rodata (constants), .data (init globals), .bss (uninit
      globals) and the .symtab (symbol table).
    - .bss has type NOBITS -- it takes NO space in the file; the OS just
      zero-fills that memory at load time.

--------------------------------------------------------------------------------
$ readelf -l ./hello_world          (Program Headers / LOAD segments)
--------------------------------------------------------------------------------
Where "sections" (readelf -S) are the LINKER's view, "segments" (readelf -l)
are the LOADER's view -- they describe how the OS maps the file into the
initial process address space (which VirtAddr, how big, and with what r/w/x
permissions). Many sections get grouped into one segment.

Elf file type is DYN (Position-Independent Executable file)
Entry point 0x1080
There are 13 program headers, starting at offset 64

  Type           Offset             VirtAddr           FileSiz   MemSiz   Flg
  PHDR           0x0000000000000040 0x0000000000000040 0x0002d8  0x0002d8  R
  INTERP         0x0000000000000318 0x0000000000000318 0x00001c  0x00001c  R
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
  LOAD           0x0000000000000000 0x0000000000000000 0x0007d8  0x0007d8  R
  LOAD           0x0000000000001000 0x0000000000001000 0x0001b1  0x0001b1  R E
  LOAD           0x0000000000002000 0x0000000000002000 0x0000fc  0x0000fc  R
  LOAD           0x0000000000002d98 0x0000000000003d98 0x000278  0x0003c0  RW
  DYNAMIC        0x0000000000002da8 0x0000000000003da8 0x000200  0x000200  RW
  NOTE           0x0000000000000338 0x0000000000000338 0x000030  0x000030  R
  NOTE           0x0000000000000368 0x0000000000000368 0x000044  0x000044  R
  GNU_PROPERTY   0x0000000000000338 0x0000000000000338 0x000030  0x000030  R
  GNU_EH_FRAME   0x0000000000002018 0x0000000000002018 0x000034  0x000034  R
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x000000  0x000000  RW
  GNU_RELRO      0x0000000000002d98 0x0000000000003d98 0x000268  0x000268  R

 Section to Segment mapping (which sections land in each LOAD segment):
   02  .interp .note.* .gnu.hash .dynsym .dynstr .gnu.version* .rela.*  (R  )
   03  .init .plt .plt.got .plt.sec .text .fini                        (R E) <-- code
   04  .rodata .eh_frame_hdr .eh_frame                                 (R  ) <-- constants
   05  .init_array .fini_array .dynamic .got .data .bss                (RW ) <-- data + bss

   Segment Sections...
   00     
   01     .interp 
   02     .interp .note.gnu.property .note.gnu.build-id .note.ABI-tag .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt 
   03     .init .plt .plt.got .plt.sec .text .fini 
   04     .rodata .eh_frame_hdr .eh_frame 
   05     .init_array .fini_array .dynamic .got .data .bss 
   06     .dynamic 
   07     .note.gnu.property 
   08     .note.gnu.build-id .note.ABI-tag 
   09     .note.gnu.property 
   10     .eh_frame_hdr 
   11     
   12     .init_array .fini_array .dynamic .got 

  Notes:
    - The 4 LOAD segments are exactly what the OS mmap()s into memory. Their
      permissions match intuition:
        R E  --> code   (readable + executable, NOT writable)
        R    --> constants (read-only)
        RW   --> data + bss (read + write)
    - Look at the last LOAD: FileSiz 0x278 but MemSiz 0x3c0. The extra
      0x148 bytes are .bss -- present in memory, absent in the file (NOBITS),
      zero-filled by the loader. This is the file->memory size gap in action.
    - INTERP names the dynamic linker (/lib64/ld-linux-x86-64.so.2) -- the
      program that pulls in shared libraries at startup (the ".so libs" and
      "ASLR base" that the ELF itself does NOT contain).
    - GNU_STACK has flags RW (not X) -- a non-executable stack, a security
      hardening default.
================================================================================
*/

/*
================================================================================
DOES THE ELF DESCRIBE THE PROCESS ADDRESS SPACE ?
================================================================================
Short answer: PARTIALLY -- it describes the initial, file-backed BLUEPRINT of
the address space, but NOT the full runtime address space. The complete address
space is assembled by the OS loader at launch and keeps changing at runtime.

--------------------------------------------------------------------------------
TWO VIEWS OF THE SAME FILE
--------------------------------------------------------------------------------
    readelf -S  --> SECTIONS  (.text, .data, ...)  --> the LINKER's view (build)
    readelf -l  --> SEGMENTS  (LOAD, DYNAMIC, ...)  --> the LOADER's view (run)

The address-space mapping comes from the SEGMENTS. Each LOAD segment says:
"take these bytes from the file, map them at this VirtAddr, with these r/w/x
permissions." That is the part of the address space the ELF defines.

Header fields that prove it is describing a MEMORY layout (not just disk bytes):
    - Entry point address (e.g. 0x1080) --> virtual address where exec starts
    - VirtAddr column in readelf -l      --> target virtual addresses

--------------------------------------------------------------------------------
WHAT ELF DESCRIBES  vs  WHAT THE OS ADDS AT RUNTIME
--------------------------------------------------------------------------------
    Region                     | From ELF ?
    ---------------------------|--------------------------------------------
    .text / .rodata / .data    | YES  (LOAD segments)
    .bss (zero-filled)         | DESCRIBED, but no bytes in file (NOBITS);
                               |   seen as the FileSiz < MemSiz gap in -l
    Heap (malloc / new)        | NO   -- created & grown at runtime
    Stack                      | NO   -- set up by the OS at launch
    Shared libraries (.so)     | NO   -- mapped in by the dynamic linker
                               |   (named via INTERP: ld-linux-x86-64.so.2)
    Randomized base (ASLR)     | NO   -- chosen by the OS each run

The last row connects to Type: DYN (PIE). Because the binary is
position-independent, the addresses in the ELF are effectively RELATIVE -- the
OS is free to slide everything to a random base address at load time. So the
file gives a RELATIVE template; the OS decides the ABSOLUTE final layout.

--------------------------------------------------------------------------------
MENTAL MODEL
--------------------------------------------------------------------------------
    ELF file --(loader reads LOAD segments)--> initial address space
                                                     |
                        runtime adds: heap, stack, .so libs, ASLR offset
                                                     v
                                          actual process address space

IN ONE LINE:
ELF describes the initial, file-backed regions of the address space (code +
data, as a relocatable template), but the COMPLETE process address space is
assembled by the OS at load time and grows at runtime.
================================================================================
*/
