// Author: Yash Deshpande
// Date  : 06-08-2026
// Tutor : Jack Sorber (https://youtu.be/GV10eIuPs9k?si=NjMyUHnaQI80j_8m)

// Random Number generator that crashes when the random number is 13.  

// Compile: gcc -g 3_core_dump.c
// Run    : ./a.out
// Check size of core dump : ulimit -c 
// Set size of core dump: ulimit -c unlimited 
// Run gdb: gdb ./a.out core.340204

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <stdbool.h>
#include <unistd.h>

int main() {
    int rnum = 0;
    int* goodptr = malloc(sizeof(int));
    int* badptr = NULL;

    srand(time(NULL));
    while(true) {
        rnum = rand() % 255;
        if(rnum == 13) {
            *badptr = rnum;
        }
        else {
            *goodptr = rnum;
        }
        printf("random: %d\n", rnum);
        // sleep(1);            --> takes too long to crash/simulates real program
        usleep(100);         // --> for faster crashes/study purpose
    }
    return 0;
}

// Output 
// Segmentation fault (core dumped)


// gdb of the core dump 

// Core was generated by `./a.out'.
// Program terminated with signal SIGSEGV, Segmentation fault.
// #0  0x0000599bfe74d261 in main () at 3_core_dump.c:28
// 28                  *badptr = rnum;
// (gdb) p *badptr
// Cannot access memory at address 0x0
// (gdb) p badptr
// $1 = (int *) 0x0