// Author: Yash Deshpande
// Date  : 30-07-2026
// Tutor : Striver

// NOTE: WORK IN PROGRESS. These notes are unfinished — fact-check every claim
//       here whenever you return to them before relying on any of it.

// Striver has only taught to write recursive approach -> memoize -> tabulate -> space-opt

// But in the questions done so far this approach has only been demonstrate in 
// questions that can be written in recursion in a top-down manner

// If recursion is written in a bottom-up manner, I currently don't know how to tabulate.

// There are 2 buckets of problems
// 1. jump1 or jump2
// 2. take or notTake (all subsequence)
// 3. grid (unique paths)

// Either prevent recursion through 
// 1. base case
// 2. conditional recursive call

// LIS & LCS are 2 important questions that use shifting-of-index but for very different reasons
// Hence method to shift differs
// LCS => can't tabulate without shift-of-index
// LIS => can't even meoize without shift-of-index

// -------------------- Top-Down vs Bottom-Up --------------------
// Disclaimer: explanation generated by Claude (Opus 4.8) on 2026-07-30.
//
// These are DEFINED by the technique, not by how the index moves:
//   Top-Down  = memoized recursion   (the two are synonyms)
//   Bottom-Up = iterative tabulation (the two are synonyms)
// So recursion (memoized or not) is ALWAYS top-down.
//
// "Top" and "bottom" refer to problem SIZE, not the direction the index moves:
//   Top    = the full problem you were asked (e.g. solve(n-1))
//   Bottom = the base case / smallest subproblem (e.g. index 0)
//
// Why recursion is always top-down (structural reason):
//   Recursion must start at the full problem and break it into smaller calls.
//   The base cases return FIRST (they resolve at the bottom of the call stack)
//   and the full answer is assembled LAST. That "ask the big question, descend
//   to the small ones" flow IS what top-down means. Memoization only adds a
//   cache; it does not change the direction.
//
// The proof that index direction doesn't matter is right in your own files:
//   Frog Jump (3_Frog_Jump.cpp)  : solve(n-1) -> base n==0   (index n->0)
//   LIS       (41_..._subseq.cpp): solve(0,-1) -> base ind==n (index 0->n)
//   Both are memoization / top-down, even though the indices move OPPOSITE ways.
//   What makes them top-down is that you asked for the big answer and recursion
//   broke it down -- not which way the index counts.
//
// Caveat (so the rule isn't a lie): you *could* contrive a recursive helper that
// fills dp[0], dp[1], dp[2]... in increasing order like a loop -- that is a loop
// wearing a recursion costume, and nobody writes DP that way. For every problem
// in this folder the clean rule holds.
//
// Rule of thumb: recursion => Top-Down.  for-loop filling a table => Bottom-Up.
//                Ignore which way the index moves.