// Author : Yash Deshpande
// Date   : 12-07-2026
// Tutor  : Striver

#include <iostream>
#include <bits/stdc++.h>
using namespace std;

class Solution_Recursion {
    int solve(int ind, int prev_ind,vector<int>& arr, int n) {
        if(ind == n) return 0;

        int len = 0 + solve(ind+1, prev_ind, arr, n);
        // Why the condition must be `prev_ind == -1` and NOT `ind == 0` ? 
        if(prev_ind == -1 || arr[ind] > arr[prev_ind]) {
            len = max(len, 1 + solve(ind+1, ind, arr, n));
        }
        return len;
    }
public:
    int lengthOfLIS(vector<int>& nums) {
        return solve(0, -1, nums, nums.size());
    }
};

// Memoization
class Solution_Memoization {
    int solve(int ind, int prev_ind,vector<int>& arr, int n, vector<vector<int>> dp) {
      if(ind == n) return 0;

      if(dp[ind][prev_ind+1] != -1) {
        return dp[ind][prev_ind+1   ];
      }

      int len = 0 + solve(ind+1, prev_ind, arr, n, dp);
      if(prev_ind == -1 || arr[ind] > arr[prev_ind]) {
          len = max(len, 1 + solve(ind+1, ind, arr, n, dp));
      }
      return dp[ind][prev_ind+1] = len;
  }
public:
    int lengthOfLIS(vector<int>& nums) {
        vector<vector<int>> dp(nums.size(), vector<int>(nums.size()+1, -1));
        return solve(0, -1, nums, nums.size(), dp);
    }
};


int main() {
    return 0;
}
/*

############################################## Extra Notes #####################################################

Disclaimer: explanation generated by Claude (Opus 4.8) on 2026-07-28.

Why the condition must be `prev_ind == -1` and NOT `ind == 0`
------------------------------------------------------------
`prev_ind == -1` encodes a STATE: "no element has been picked yet", so there is
no previous value to compare against and the current element can always be taken.
`ind == 0` encodes a POSITION: "we are at the first index".

These two are equal only at the very start. Because prev_ind stays -1 on every
"skip" branch, we can reach ind = 3 with prev_ind still -1 (we skipped 0, 1, 2).
In that case `ind == 0` is false, so C++ evaluates the right side
`arr[ind] > arr[prev_ind]` -> arr[-1], an out-of-bounds read (undefined behavior).
With `prev_ind == -1`, short-circuit evaluation stops before ever touching arr[-1].

Rule of thumb: when two conditions look interchangeable, check whether they encode
the same invariant across ALL reachable states, not just the initial one. Confirm
suspected index bugs with arr.at(ind) or -fsanitize=address,undefined.

*/