#include <iostream>
#include <queue>
#include <string>
#include <sstream>                  // --> for stringstream
using namespace std;

// Definition for a binary tree node.
struct TreeNode
{
    int val;
    TreeNode *left;
    TreeNode *right;
    TreeNode(int x) : val(x), left(NULL), right(NULL) {}
};

class Codec {
public:
    // Encodes a tree to a single string.
    string serialize(TreeNode *root) {
        // Level Order Traversal
        string ans = "";

        if (root == nullptr) {
            return ans;
        }

        queue<TreeNode *> q;
        q.push(root);

        while (!q.empty()) {
            auto frontNode = q.front();
            q.pop();

            if (frontNode == nullptr) {
                ans += "#,";
            }
            else {
                ans += to_string(frontNode->val) + ",";
                q.push(frontNode->left);
                q.push(frontNode->right);
            }
        }
        return ans;
    }

    // Decodes your encoded data to tree.
    TreeNode *deserialize(string data)
    {
        if (data.size() == 0){
            return nullptr;
        }

        stringstream ss(data);
        string str;

        getline(ss, str, ',');
        TreeNode *root = new TreeNode(stoi(str));

        queue<TreeNode *> q;
        q.push(root);

        while (!q.empty()){
            auto frontNode = q.front();
            q.pop();

            getline(ss, str, ',');
            if (str == "#"){
                frontNode->left = nullptr;
            }
            else{
                frontNode->left = new TreeNode(stoi(str));
                q.push(frontNode->left);
            }

            getline(ss, str, ',');
            if (str == "#"){
                frontNode->right = nullptr;
            }
            else{
                frontNode->right = new TreeNode(stoi(str));
                q.push(frontNode->right);
            }
        }
        return root;
    }
};

int main()
{
    return 0;
}

// ############################################################################
// NOTES : The notes section below was generated by an LLM (Claude Opus 4.8)
//         on 14-07-2026. Please verify before relying on it.
// ############################################################################
//
// ============================================================================
// stringstream (from <sstream>)
// ============================================================================
//
// ONE-LINE IDEA:
// std::stringstream (from <sstream>) is a stream that reads from and writes to 
// a string in memory, instead of the console (cout/cin) or a file. It
// gives you the same << and >> operators you already use with I/O streams, but 
// the "source"/"destination" is a string buffer.

//   stringstream is a string you can treat like cin / cout.
//   (A string wearing a cin/cout costume.)
//
//
// MENTAL MODEL:
//   Normally --   cout <<  sends data TO the screen
//                 cin  >>  reads data FROM the keyboard
//   stringstream is the same, but it talks to a STRING instead:
//       <<              puts data INTO  the string  (build)
//       >> / getline    pulls data OUT of the string (parse)
//
//
// TWO USES:
//   1. BUILD -- glue numbers + text together:
//          stringstream ss;
//          ss << "id" << 5;      // stuff goes in
//          ss.str();             // "id5"  <- get the string out
//
//   2. PARSE -- chop a string into pieces:
//          stringstream ss("a,b,c");
//          string x;
//          getline(ss, x, ',');  // x = "a", then "b", then "c"
//                                 // 3rd arg is the delimiter (default '\n')
//
//
// HOW IT IS USED IN THIS FILE (deserialize):
//   The serialized tree is one string like "1,2,#,#,3,#,#,".
//       stringstream ss(data);       // load the string into a stream
//       getline(ss, str, ',');       // peel off one node value per comma
//   Each getline reads up to the next ',' and advances past it, letting us
//   rebuild the tree token by token.
//
//
// WHY IT FITS SERIALIZE / DESERIALIZE:
//   - serialize()   uses '+=' / to_string to append values + ',' into one string.
//   - deserialize() uses getline(..., ',') to walk back through those tokens.
// ============================================================================
