// Author : Yash Deshpande
// Date : 31-01-2022 

#include <iostream>
using namespace std;

class Complex
{
    int a, b;

public:
    // Creating a Constructor

    // Method-0: Don't declare any constructor --------------------------- // 
    // The compiler generates an implicit default constructor 
    // only if you declare NO constructors at all.

    // Method-1: User-defined default constructor ------------------------ // 
    Complex(void); // Constructor declaration

    // Method-2: ask the COMPILER to generate it -------------------------- // 
    // Complex() = default;   

    void printNumber()
    {
        cout << "Your number is " << a << " + " << b << "i" << endl;
    }
};

Complex ::Complex(void) // ----> This is a default constructor as it takes no parameters
{
    a = 0;
    b = 0;
    // cout<<"Hello world";
}

int main()
{
    Complex c1, c2, c3;
    c1.printNumber();
    c2.printNumber();
    c3.printNumber();

    /*
    -------------- output --------------
    Your number is 0 + 0i
    Your number is 0 + 0i
    Your number is 0 + 0i
    */

    return 0;
}


/*  

##############################################Extra Notes#####################################################s

1. Constructor is a special member function with the same name as of the class.
    
2. It is used to initialize the objects of its class
    
3. It is automatically invoked whenever an object is created

4. Characteristics of Constructors

    1. It should be declared in the public section of the class 
    2. They are automatically invoked whenever the object is created 
    3. They cannot return values and do not have return types
    4. It can have default arguments 
    5. We cannot refer to their address

5. Difference between the two default-constructor declarations
   [Note generated by LLM (Cursor, Claude Opus 4.8) on 10-07-2026]

    Method-1 : Complex(void);        --> user-defined default constructor
    Method-2 : Complex() = default;  --> compiler-generated default constructor (C++11)

    a) Who writes the logic
        - Method-1: YOU write the body and decide what happens.
        - Method-2: The COMPILER synthesizes the constructor for you.

    b) Member initialization
        - Method-1: Members are set exactly as you code them (here a = 0, b = 0),
          so printNumber() reliably shows "0 + 0i".
        - Method-2: Members are NOT initialized for primitive types (int here),
          so a and b hold garbage values unless you add in-class initializers
          (e.g. int a = 0, b = 0;).

    c) Syntax / history
        - Method-1: 'void' in the params is old C-style and is optional in C++.
        - Method-2: Uses empty () and was introduced in C++11.

    d) Equivalence
        - They behave the same ONLY if the compiler-generated version ends up
          initializing the members the way you want (which needs default member
          initializers for primitive types).

    e) Then why do we even need "= default" ?
        - When you need a parameterized constructor and still want the free 
          compiler-generated default one back, you use = default:
        - The compiler auto-generates a default constructor ONLY when you
          declare ZERO constructors. Declaring any constructor (e.g. a
          parameterized one) suppresses it, and "= default" brings it back.
        - Prefer "= default" over an empty A() {} : it keeps the type TRIVIAL
          (good for optimizations, std::is_trivial, POD-ness), while A() {}
          makes it NON-trivial.

    NOTE: Declaring BOTH Method-1 and Method-2 in the same class (as shown
    above) is only for comparison. In real code it is a compile error (the
    default constructor would be declared twice). Keep just one: hand-write it
    when you need custom logic, else use "= default".

*/
