// Author : Yash Deshpande
// Date : 31-01-2022

// ##########################################################################
// NOTE: This file also looks at the two forms of initializing an object:
//       direct initialization and copy initialization.
// ##########################################################################

#include <iostream>
using namespace std;

class Complex
{
    int x,y;
    public:
    Complex(int, int);  // Constructor declaration
    void printNumber(void)
    {
        cout<<"The number is "<<x<<" + "<<y<<"i"<<endl;
    }

};

Complex :: Complex(int a, int b)  // ----> This is a parameterized constructor as it takes 2 parameters
{
    x = a;
    y = b;
}

int main()
{
    // Direct initialization
    Complex c1(4, 6);
    c1.printNumber();

    // Copy initialization (copy is elided; since C++17 it is constructed in place)
    Complex c2 = Complex(5, 7);
    c2.printNumber();
    
    return 0;
}

/*

##############################################Extra Notes#####################################################s

1. Parameterized constructors are those constructors that take one or more parameters.

2. Default constructors are those constructors that take no parameters.

3. Terminology: direct initialization vs copy initialization
   [Generated by Claude Opus 4.8, 10-07-2026]

    Complex c1(4, 6);            --> direct initialization
    Complex c2 = Complex(5, 7);  --> copy initialization

    - AVOID calling these "implicit" / "explicit" calls. In C++ those words
      are tied to the 'explicit' keyword and to implicit CONVERSIONS, so
      reusing them here is misleading.

    - Direct initialization: the constructor is invoked directly using ().

    - Copy initialization: syntactically a temporary Complex(5, 7) is created
      and c2 is initialized from it. In practice the copy is elided
      (guaranteed since C++17), so it is constructed directly in place. The
      *form* is still copy initialization.

    - The real "explicit vs implicit" distinction is about conversions:
        Complex c3 = 5;   // implicit conversion (needs a Complex(int) ctor that is NOT explicit)
        Complex c4(5);    // direct init — works even if the ctor is 'explicit'
      Marking a constructor 'explicit' blocks the '=' conversion form but
      still allows direct initialization.

*/