// Author : Yash Deshpande
// Date   : 31-01-2022
// Tutor  : Code with Harry 

#include<iostream>
using namespace std;

// Note: This class has only value members (no pointers/dynamic allocation), 
// so a shallow copy and a deep copy are identical here.
class Number{
    int a;
    public:
        Number() {a = 0;}
        Number(int num) {a = num;}
        
        // When no copy constructor is found, compiler supplies its own copy constructor
        // Note : The Parameter passed when defining a copy constructor is always 
        //        "Pass by Reference" hence the "&" sign is used 
        // Number(Number &obj){
        //     cout<<"Copy constructor called!!!"<<endl;
        //     a = obj.a;
        // }

        // The const is optional but is added so that we do not modify the obj by mistake. 
        // Flexibility: lets you copy from const objects and temporaries (rvalues)
        // Copy constructor takes a reference to an object of the same class as an argument.
        // NOTE : You can access the private data members of the passed object.
        Number(const Number &obj){
            cout<<"Copy constructor called!!!"<<endl;
            a = obj.a;
        }

        void display(){
            cout<<"The number for this object is "<< a <<endl;
        }
};
int main(){
    Number x, y, z(45), z2;
    x.display();
    y.display();
    z.display();

    // Case-1: Copy constructor invoked
    Number z1(z); 
    z1.display();

    // Case-2: Copy constructor invoked
    Number z3 = z; 
    z3.display();

    // Case-3: Copy constructor NOT called  --> copy assignment operator
    z2 = z; 
    z2.display();

    // z1 should exactly resemble z  or x or y

    return 0;
}


/*

##############################################Extra Notes#####################################################s

1. A copy constructor is a type of constructor that creates a copy of another object. 

2. If we want one object to resemble another object we can use a copy constructor. 

3. If no copy constructor is written in the program, compiler will supply its own copy constructor.

4. When no copy constructor is found, compiler supplies its own copy constructor
   for e.g. : Number z1(z);  --> will generate an automatic copy constructor if none is explicitly declared by the programmer

5. Default copy constructor does shallow copy 

6. User defined copy constructor does deep copy

// --- Disclaimer: The following point was generated by an LLM (Claude Opus 4.8) on 11-07-2026 ---

7. Why must a copy constructor take its parameter by reference (&) and not by value?
   - Passing an argument BY VALUE requires the compiler to make a copy of that argument first.
   - Making a copy of a Number is done by calling the copy constructor.
   - So a copy constructor taking its parameter by value would need to call the copy
     constructor to receive its own argument -> which again needs a copy -> infinite recursion.
   - Because of this, C++ forbids it: Number(Number obj) is a compile error.
   - A reference (Number &obj) is just an alias to the existing object, so no copy is made
     to bind it, breaking the recursion. The 'const' is optional but recommended, as it
     prevents accidental modification of the source and allows copying from const/temporary objects.

// --- Disclaimer: The following point was generated by an LLM (Claude Opus 4.8) on 11-07-2026 ---

8. Shallow copy vs Deep copy (and why it makes no difference for THIS class):
   - Shallow copy: copies each member's value bit-for-bit; for a pointer this copies the ADDRESS,
     so both objects end up sharing the SAME heap memory (risking double-free / unintended aliasing).
   - Deep copy: for a pointer it allocates NEW memory and copies the pointed-to contents,
     so each object owns its OWN independent copy.
   - The distinction ONLY matters when a class owns memory through a pointer (indirection).
   - This Number class has only a value member (int a) and no pointers/dynamic allocation,
     so there is nothing deeper to follow -> shallow and deep copy produce identical, safe results.

*/