// Author : Yash Deshpande
// Date   : 20-09-2025
// Tutor  : GFG (https://www.geeksforgeeks.org/cpp/cpp-assignment-operator-overloading/)

#include <iostream>
#include <cstring>
using namespace std;

// In C++, the compiler automatically provides a default assignment operator for classes.
// This operator performs a shallow copy of each member of the class from one object to another.
// If our class has dynamic memory allocation, then shallow copy will cause double free error.

class GfG
{
public:
    int *arr;
    int _size;

    // Parameterized Constructor
    GfG(int size = 3)
    {
        arr = new int[size];
        _size = size;
    }

    //  ############### COMMENT THIS SECTION AND CHECK OUTPUT ###############
    // Overloaded assignment operator
    GfG& operator=(const GfG &c)
    {
        // self assignment guard                        -> address comparison
        // Why  `if (*this != c)` is not equivalent ?   -> value comparison
        if (this != &c)
        {
            // Allocate new block
            int *temp = arr;
            arr = new (nothrow) int[c._size];

            // If allocation fails
            if (arr == nullptr)
            {
                arr = temp;
            }
            else
            {
                // Deallocate current block
                delete[] temp;

                // Copy data
                _size = c._size;
                memmove(arr, c.arr, _size * sizeof(int));
            }
        }
        return *this;
    }
    // #######################################################################

    // Deleting dynamic resources
    ~GfG()
    {
        delete[] arr;
    }
};

int main()
{
    GfG c1, c2;

    // Initialize c2.arr with some values
    for (int i = 0; i < c1._size; i++) {
        c2.arr[i] = i + 10;
    }

    // Copying c2 object to c1
    c1 = c2;

    // Print the pointers to the allocated memory
    cout << c1.arr << endl;
    cout << c2.arr;
    return 0;


    /*
    Output with Shallow Copy ----------------------------------------
    0x6282e871e2d0
    free(): double free detected in tcache 2
    Aborted (core dumped)

    Output with Deep Copy --------------------------------------------
    0x5776bb7d52f0
    0x5776bb7d52d0
    
    */
}

/*

#################################### Extra Notes ############################################

Refer to this article : https://www.geeksforgeeks.org/cpp/cpp-assignment-operator-overloading/

In C++, the compiler automatically provides a default assignment operator for classes.
This operator performs a shallow copy of each member of the class from one object to another.
This means that if we don't explicitly overload the assignment operator,
the compiler will still allow us to assign one object to another using the assignment operator (=),
and it won't generate an error.

So, when we should perform assignment operator overloading?
When our class involves dynamic memory allocation (e.g., pointers) and we need to perform a deep copy
to prevent issues like double deletion or data corruption.


// ---------------------------------------------------------------------------
// DISCLAIMER : The note below was generated by an AI assistant (Cursor, model
//              Opus 4.8). Added on 11-07-2026. Please verify before relying on it.
// ---------------------------------------------------------------------------

--- Standard syntax of the copy assignment operator ---------------------------

The canonical (textbook) signature is:

        ClassName& operator=(const ClassName& other);

In this file that maps to:  GfG& operator=(const GfG &c)

Breaking down each part:

    1. GfG&  (return by reference)
       -> Returns a reference to the object being assigned to (*this).
       -> Enables chaining like  a = b = c;  and avoids making an extra copy
          of the returned object.

    2. operator=
       -> The special function name that overloads the '=' assignment operator.

    3. const GfG &c  (const reference parameter)
       -> Takes the source object by reference, so no copy is made.
       -> 'const' promises that the source object 'c' will not be modified.

    4. return *this;  (inside the function body)
       -> Returns the object that was assigned to, which is what makes the
          chaining in point (1) possible.

Optional modern refinements (beyond this example's scope):
    - Copy-and-swap idiom: take the parameter by value and swap, giving strong
      exception safety and automatic self-assignment handling.
    - In C++11+, also add a move assignment operator:
          GfG& operator=(GfG&& c) noexcept;

--------------------------------------------------------------------------------

--- Self-assignment check: (this != &c) vs (*this != c) -----------------------

These two are NOT equivalent; they compare completely different things.

    (this != &c)   -> ADDRESS comparison.
                      'this' is a pointer to the current object; '&c' is the
                      address of the source object. This asks "are these the
                      SAME object in memory?". This is the correct
                      self-assignment guard (protects against  x = x;  where
                      we would otherwise delete[] our own array before copying).

    (*this != c)   -> VALUE comparison.
                      '*this' and 'c' are the actual objects, so this compares
                      their CONTENTS. It requires an overloaded operator!= and
                      has different semantics: two distinct objects with equal
                      values would be treated as "equal", so a real assignment
                      (e.g. a = b) could be wrongly skipped.

Rule of thumb: a self-assignment guard must always use the ADDRESS comparison
(this != &c), never the value comparison.

--------------------------------------------------------------------------------

*/