// Author : Yash Deshpande
//
// ############################################################################
// DISCLAIMER : The notes in this file were generated by an LLM (Claude Opus 4.8)
//              on 12-07-2026. This is a comments-only reference file (no
//              executable code). Please verify before relying on it.
// ############################################################################
//
// Topic : Compiler-provided (implicit) special member functions & shallow copy
//
//
// ============================================================================
// 1. THE SIX SPECIAL MEMBER FUNCTIONS
// ============================================================================
//
// For a class T, C++ can implicitly provide SIX special member functions if the
// user does not declare them:
//
//     Special member function        Signature (for class T)     Auto-generated?
//     ----------------------------------------------------------------------------
//     Default constructor            T()                          Yes, but ONLY if
//                                                                 you declare NO
//                                                                 other constructor
//     Destructor                     ~T()                         Yes (always,
//                                                                 unless deleted)
//     Copy constructor               T(const T&)                  Yes
//     Copy assignment operator       T& operator=(const T&)       Yes
//     Move constructor               T(T&&)                       Yes (C++11+,
//                                                                 conditionally)
//     Move assignment operator       T& operator=(T&&)            Yes (C++11+,
//                                                                 conditionally)
//
// NOTE: A PARAMETERIZED constructor is NEVER auto-generated. You always write
//       those yourself. (This is why a class with a parameterized constructor
//       must add an explicit default constructor if it still needs one.)
//
//
// ============================================================================
// 2. THE TWO IMPORTANT SUPPRESSION RULES
// ============================================================================
//
//   a) Declare ANY constructor (e.g. a parameterized one)
//        --> the DEFAULT constructor is NOT generated.
//
//   b) Declare a copy ctor, copy assignment, OR destructor
//        --> the MOVE operations are NOT generated (they silently fall back to
//            copying). This is a subtle C++11 rule tied to the Rule of Three/Five.
//
//
// ============================================================================
// 3. WHICH ONES DO A SHALLOW COPY?
// ============================================================================
//
// The compiler-generated COPY and MOVE operations perform a MEMBER-WISE
// copy/move, which is SHALLOW for pointer members:
//
//     Auto-generated function          Copy behaviour
//     ----------------------------------------------------------------------------
//     Copy constructor  T(const T&)     Member-wise --> SHALLOW for pointers
//     Copy assignment   operator=       Member-wise --> SHALLOW for pointers
//     Move ctor / move assignment       Member-wise move (steals the pointer)
//     Default constructor / destructor  N/A (they do not copy anything)
//
// KEY CLARIFICATION on "shallow":
//   - Member-wise copy is NOT always shallow.
//   - For VALUE members (e.g. int health, char level) it copies the actual
//     value, which is perfectly correct.
//   - It is only "shallow" for POINTER members (e.g. char *name, int *arr),
//     where it copies the ADDRESS rather than the pointed-to data.
//
//   So:
//     - Class with only value members  --> default copy is fine (shallow == deep).
//     - Class owning a raw pointer      --> default copy is a BUG (aliasing -->
//       double free). This is exactly what 4h_copy_constructor_2.cpp (copy ctor)
//       and 4i_copy_assignment_operator.cpp (copy assignment) demonstrate.
//
//
// ============================================================================
// 4. THE RULE OF THREE / FIVE / ZERO
// ============================================================================
//
// If a class manages a resource (owns a raw pointer), the defaults are wrong
// and you must define them yourself:
//
//   - Rule of Three (C++98) : destructor + copy constructor + copy assignment
//   - Rule of Five  (C++11) : those three + move constructor + move assignment
//   - Rule of Zero  (modern): use std::string, std::vector, smart pointers, etc.
//     so you own no raw resource and can safely rely on ALL the defaults.
//
//
// ============================================================================
// RELATED FILES IN THIS DIRECTORY
// ============================================================================
//   - 4g_copy_constructor.cpp          : copy constructor basics
//   - 4h_copy_constructor_2.cpp        : shallow vs deep copy via copy ctor (char *name)
//   - 4i_copy_assignment_operator.cpp  : shallow vs deep copy via operator= (int *arr)
//
