// Author : Yash Deshpande
// Date : 15-10-2022
// Tutor : Love Babbar

// To show the deep copy & shallow copy semantics of a copy constructor.

#include <bits/stdc++.h>
using namespace std;

class Hero
{
    private:
    int health;

    public : 
    char level;
    char *name;

    
    // default constructor
    Hero()
    {
        cout<<"Default Constructor called"<<endl;
        health = 100;
        level = 'A';
        name = new char [10];
    }

    // Parameterized Constructor
    Hero (int health, char lvl)
    {
        cout<<"Parameterized Constructor called"<<endl;
        this->health = health;
        this->level = lvl;
    }


    // Copy Constructor
    // Hero(Hero &temp)
    // {
    //     cout<<"Copy Constructor called"<<endl;
    //     this->health = temp.health;
    //     this->level = temp.level;

    //     char *ch = new char [strlen(temp.name) + 1];
    //     strcpy(ch, temp.name);
    //     this->name = ch;
    // }

    // Comment out the copy constructor to analyze shallow copy
    // IF no copy constructor is definded
    // hence the compiler will supply its 
    // default copy constructor
    // Shallow copy only affects dynamically allocated data members.
    

    // ###################################################################################
    // Note that this code doesn't have a destructor for dynamically allocated memory,
    // So you won't have any double free errors but you would leak memory when the objects 
    // go out of scope.
    // Read Extra Notes for detailed explanation
    // ###################################################################################

    void setHealth (int health)
    {
        this->health = health;
    }

    void setName (char charName[])
    {
        name = new char [10];
        strcpy(name, charName);
    }

    void print()
    {
        cout<<"Hero : ";
        cout<<"health = "<<this->health<<" , ";
        cout<<"Level = "<<this->level<<" , ";
        cout<<"Name = "<<this->name<<endl;
        cout<<endl;
    }

};

int main()
{
    // Creating an Object h1
    Hero h1(150, 'Z') ;
    char heroName [7] = "Babbar";
    h1.setName(heroName);
    cout<<"Printing h1"<<endl;
    h1.print();

    Hero h2(h1);
    cout<<"Printing h2"<<endl;
    h2.print();


    // Modifications made to h2
    cout<<endl<<"After modifying h2"<<endl;     // Outcome of default copy constructor 
    h2.setHealth(175);                          // Modified only in h2
    h2.name[0] = 'G';                           // Modified in BOTH h1 & h2 if default copy constructor.
    h2.level = 'Y';                             // Modified only in h2
    cout<<"Printing h2"<<endl;
    h2.print();


    cout<<"Printing h1"<<endl;
    h1.print();

    return 0;
}


/*

############################################## Extra Notes #####################################################

// --- Disclaimer: The following notes were generated by an LLM (Claude Opus 4.8) on 11-07-2026 ---

Topic : Memory management when a class holds dynamically allocated memory (the 'name' pointer)

1. The Hero class allocates heap memory with 'new' (see setName / default constructor), but it has
   NO destructor, so the matching 'delete' never runs.

2. Memory Leak (what actually happens here):
   - When main() ends, h1 and h2 are destroyed and their 'name' pointers disappear,
     but the char arrays they pointed to on the heap are never freed -> memory leak.
   - Harmless here since the program exits immediately, but dangerous in long-running programs.

3. Shallow Copy (current behaviour):
   - The copy constructor is commented out, so the compiler supplies a DEFAULT copy constructor
     that does a SHALLOW copy (copies the pointer value, not the pointed-to data).
   - After 'Hero h2(h1);' both h1.name and h2.name point to the SAME heap array.
   - That is why 'h2.name[0] = 'G';' also changes h1's name -> they share the same memory.

4. Double Free (what WOULD happen if a destructor existed + shallow copy):
   - If we added a destructor doing 'delete[] name;', then h2's destruction frees the array,
     and h1's destruction tries to free the SAME array again -> double free -> crash / UB.

5. Why the in-code comment says "you won't have any double free errors":
   - Because there is no destructor, 'delete' is never called -> no double free,
     but nothing is freed either -> memory is leaked instead.

6. Correct fix for real code:
   - Uncomment the deep-copy copy constructor (each object gets its OWN copy of 'name'),
     AND add a destructor with 'delete[] name;'. Then every object owns and cleans up its
     own memory: no leak and no double free.

*/