// Author : Yash Deshpande
// Date   : 23-09-2025
// Tutor  : The Cherno
// https://youtu.be/fbYknr-HPYE?si=brKqzOPTlZH7yYFF

#include <iostream>
#include <string>
using namespace std;

// lvalue simply means an object that has an identifiable location in memory (i.e. having an address).
// r-value simply means, an object that has no identifiable location in memory (i.e. not having an address).
// r-values can also be referred to as "TEMPORARY"

// ###############################
// Utility functions for Example-2
// ###############################
int GetValue() {
    return 10;
}

int& GetValueRef() {
    static int value = 10;
    return value;
}

// ###############################
// Utility functions for Example-3
// ###############################
void SetValue(int& x) {}

// ###############################
// Utility functions for Example-4
// ###############################
void SetValueConst(const int& x) {}

// ###############################
// Utility functions for Example-5 : To demonstrate the use of const references, functions accept both lvalue & rvalue
// ###############################

// Function-1: Only accepting Lvalue reference
void printname(string &name) {
    cout<<"[lvalue] = "<<name<<endl;
}

// Function-2: Accepting lvalue reference & const rvalue
void printname(const string &name) {
    cout<<"[lvalue] = "<<name<<endl;
}

// Function-3: Only Accepting rvalue reference
void printname(string &&name) {
    cout<<"[rvalue] = "<<name<<endl;
}

int main() {

    // Example-1
    int i = 10;             // --> i = lvalue, 10 = rvalue
    // 10 = i;              // --> Compiler Error: Expression must be a modifiable lvalue
    int a = i;              // --> a = lvalue, i = lvalue

    // Example-2
    int j = GetValue();     // GetValue() returns an rvalue
    // GetValue() = 10;     // Compiler Error: Expression must be a modifiable lvalue
    GetValueRef() = 50;     // GetValueRef returns an lvalue reference (int&),
                            // so the returned value is an lvalue and can be assigned to

    // Example-3
    int x = 10;
    SetValue(x);
    // SetValue(10);        // Compiler Error: Cannot pass an rvalue in-place of an lvalue reference


    // Example-4
    // int &y = 10          // Compiler Error: Cannot pass an rvalue in-place of an lvalue reference
    const int &y = 10;      // Why does this work ? The compiler probably assigns some temporary storage
                            // to our rvalue 10 here.
    SetValueConst(x);
    SetValueConst(10);


    // Example-5
    // In each of the below examples 
    // LHS is a lvalue 
    // RHS is a rvalue
    string firstname = "Yan";
    string lastname = "Chernikov";
    string fullname = firstname + lastname;

    // Call to overloaded Function-1
    printname(fullname);                            // [lvalue] = YanChernikov

    // Call to overloaded Function-3
    printname(firstname + lastname);                // [rvalue] = YanChernikov
    return 0;
}

/*

##############################################Extra Notes#####################################################

// Generated by: Cursor (Claude Opus 4.8) | Date: 11-07-2026

lvalue reference & rvalue reference:
    A reference is just an alias that lets us bind to (refer to) an existing value.
    There are two kinds, based on WHAT they are allowed to bind to.

1. lvalue reference  -->  T&
    - An alias to an object that has an identifiable location in memory (an lvalue).
    - A non-const lvalue reference (T&) can ONLY bind to a modifiable lvalue.
          int i = 10;
          int& ref = i;      // OK  : i is an lvalue
          int& r   = 10;     // ERROR : 10 is an rvalue (no address to alias)
    - EXCEPTION: a const lvalue reference (const T&) CAN bind to an rvalue.
      The compiler creates a temporary and extends its lifetime to match the reference.
          const int& y = 10; // OK  (see Example-4 above)
    - This is why "const T&" is the classic "accept anything, read-only" parameter type:
      it binds to both lvalues and rvalues.

2. rvalue reference  -->  T&&   (introduced in C++11)
    - An alias that binds ONLY to rvalues (temporaries that are about to expire).
          int&& rr = 10;            // OK  : 10 is an rvalue
          int x = 5;
          int&& bad = x;            // ERROR : x is an lvalue
    - See Example-5: printname(string&&) only matches a temporary,
      e.g. printname(firstname + lastname), whereas printname(fullname) is an lvalue.

Why rvalue references exist:
    If something is a temporary (an rvalue), nobody else is using it and it is about to be
    destroyed, so we are free to STEAL its resources instead of copying them.
    This is the foundation of move semantics (move constructor / move assignment) and
    perfect forwarding (std::forward).

Quick summary:
    non-const lvalue ref (T&)        -> binds to lvalue        , NOT to rvalue
    const lvalue ref     (const T&)  -> binds to lvalue & rvalue (read-only)
    rvalue ref           (T&&)       -> binds to rvalue         , NOT to lvalue

IMPORTANT subtlety:
    A variable whose TYPE is an rvalue reference is itself an lvalue (it has a name & address).
    So inside a move constructor you must use std::move again to treat a named T&& parameter
    as an rvalue.

-------------------------------------------------------------------------------------------------

Overload resolution: which printname() gets called? (Example-5)

    Call in question:  printname(firstname + lastname);
    firstname + lastname calls operator+, which returns a TEMPORARY string --> an rvalue.

    Candidates:
        Function-1  void printname(string &name)         // T&
        Function-2  void printname(const string &name)   // const T&
        Function-3  void printname(string &&name)        // T&&

    Step 1 - Build the set of VIABLE functions (what the argument can legally bind to):
        Function-1 (string&)        -> NOT viable : a non-const lvalue ref cannot bind to an rvalue
        Function-2 (const string&)  -> viable     : a const lvalue ref can bind to an rvalue
        Function-3 (string&&)       -> viable     : an rvalue ref binds to an rvalue

    Step 2 - Rank the remaining viable functions (tie-break rule from the standard, [over.ics.rank]):
        When an rvalue can bind to BOTH an rvalue reference (T&&) and a const lvalue
        reference (const T&), the RVALUE REFERENCE is preferred.
        => Function-3 (string&&) wins, so the call prints "[rvalue]".

    Why this preference exists:
        An rvalue is a temporary about to be destroyed, so the "steal the resources"
        overload (T&&) is exactly the one we want for a temporary. This is what enables
        move semantics when both overloads are present.

Contrast - printname(fullname):
    fullname is a NAMED object --> an lvalue.
        Function-1 (string&)        -> viable
        Function-2 (const string&)  -> viable
        Function-3 (string&&)       -> NOT viable : cannot bind an rvalue ref to an lvalue
    Between Function-1 and Function-2, string& is preferred over const string& (no added
    const qualification needed), so it resolves to Function-1 and prints "[lvalue]".

Quick mental model:
    rvalue argument -> prefers T&&, falls back to const T&
    lvalue argument -> prefers T& (then const T&); can never pick T&&

*/