// Author : Yash Deshpande
// Date : 24-01-2022

// Q. Program to check if a number is prime or not

#include <iostream>
using namespace std;

bool isPrime(int num)
{
    // Guard: 0, 1 and negative numbers are not prime.
    if(num < 2)
    {
        return false;
    }

    // How is num = 2 being handled correctly here ? 
    // for: num = 2 `factor < num` is false, so the for-loop exits.
    for(int factor = 2; factor < num; factor++)
    {
        if(num % factor == 0)
        {
            return false;
        }
    }
    return true;
}

int main()
{
    int num;
    cout<<"Enter a number : ";
    cin>>num;

    if(isPrime(num))
    {
        cout<<num<<" is Prime"<<endl;
    }
    else
    {
        cout<<num<<" is Non Prime"<<endl;
    }

    return 0;
}

// ############################# EXTRA NOTES ##################################
// NOTES : The notes section below was generated by an LLM (Claude Opus 4.8)
//         on 13-07-2026. 
// ############################################################################
//
// ============================================================================
// DEFINITION OF A PRIME NUMBER
// ============================================================================
//
// A prime number is a NATURAL NUMBER GREATER THAN 1 that has exactly two
// distinct positive divisors: 1 and itself.
//
//
// ============================================================================
// RULE FOR 0, 1 & NEGATIVE NUMBERS
// ============================================================================
//
//     Number            Prime?   Why
//     ------------------------------------------------------------------------
//     Negative numbers  No       Primality is only defined for natural numbers
//                                 (positive integers). Negatives are excluded
//                                 by definition.
//     0                 No       Zero is divisible by every non-zero integer,
//                                 so it has infinitely many divisors -- nowhere
//                                 near "exactly two".
//     1                 No       It has only ONE divisor (itself). The
//                                 definition requires exactly TWO distinct
//                                 divisors, so 1 fails.
//
// So none of 0, 1, or negatives are prime. They are also not "composite" (a
// composite number is a natural number > 1 with MORE than two divisors, like
// 4, 6, 9). So 0 and 1 sit in their own category: NEITHER prime nor composite.
//
// Why 1 is specifically excluded: if 1 were prime, the Fundamental Theorem of
// Arithmetic -- that every integer has a UNIQUE prime factorization -- would
// break, since you could insert any number of 1s (e.g. 6 = 2x3 = 1x2x3 =
// 1x1x2x3 ...). Excluding 1 keeps factorizations unique.
//
// Practical takeaway for this program: anything less than 2 is "Not Prime".
// That is exactly what the if(num < 2) guard in isPrime() handles.
//
// ============================================================================

